version: '3'
services:
  postgres:
    image: postgres:10.3
    ports:
      - "5432"
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "(bundle check || bundle install) && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/make_docker_rails
    ports:
      - "3000:3000"
